--- #YAML:1.0
name:               Jamila
version:            0.03
abstract:           Perl extension for JSON Approach to Make Integration Linking Applications
author:
    - Kawai,Takanori <kwitknr@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:   ~
    JSON:  ~
    LWP:   ~
    utf8:  ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.4801
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
